from langchain_core.messages import SystemMessage, HumanMessage
from langchain_ollama import ChatOllama

from app.agents.playwright_agent import PlaywrightAgent
from app.artifacts.playwright_artifacts import PlaywrightArtifactStore
from app.mcp.client import MCPClient, mcp_config
from app.schemas.playwright import ExplorationResult
from app.schemas.test_plan import TestPlan
from app.schemas.test_registry import TestScenario, TestRecord
from app.testing.test_registry import TestRegistry
from app.validation.test_plan_validator import TestPlanValidator

PLAYWRIGHT_PLANNER_PROMPT = """
You are a Senior SDET test planner.

Create exactly ONE test case from the user's requirements
and verified browser exploration.

Rules:

1. Create exactly one test case.
2. Do not create negative scenarios.
3. Do not add unrelated functionality.
4. Do not invent application behavior.
5. Use only verified exploration evidence.
6. Every test step must have an expected result.
7. Include at least one clear precondition.
8. Classify the test as UI/API/etc.
9. Classify it as Functional or Non-functional.
10. Assign an appropriate priority using P0, P1, P2, or P3.
11. Assign at least one appropriate test suite.
12. For this happy-path login scenario, use Smoke and Regression
    where appropriate.
13. The test must be suitable for Playwright TypeScript automation.
"""


class PlaywrightPlanner:

    def __init__(self, model: str = "qwen3:8b"):
        self.llm = ChatOllama(
            model=model,
            temperature=0
        )
        self.structured_llm = self.llm.with_structured_output(TestPlan)

    async def create_plan(self, *, user_requirements: str, exploration: ExplorationResult,
                          test_case_id: str) -> TestPlan:
        messages = [
            SystemMessage(content=PLAYWRIGHT_PLANNER_PROMPT),
            HumanMessage(content=f"""
            TEST CASE ID:
            {test_case_id}
            
            USER REQUIREMENTS:
            {user_requirements}
            
            VERIFIED EXPLORATION:
            {exploration.model_dump_json(indent=2)}
            """)
        ]

        print("\n🧠 Planner: asking Qwen3...", flush=True)

        result = await self.structured_llm.ainvoke(messages)

        print("✅ Planner: test plan generated by the model.", flush=True)

        return TestPlan.model_validate(result)

    def render_markdown(self, plan: TestPlan) -> str:
        lines = [
            f"# Test Plan: {plan.title}",
            "",
            "## Test Case",
            "",
            f"- **Test Case ID:** {plan.test_case_id}",
            f"- **Priority:** {plan.priority}",
            f"- **Test Type:** {plan.test_type}",
            f"- **Test Level:** {plan.test_level}",
            f"- **Suites:** {', '.join(plan.suites)}",
            f"- **Automation:** {'Yes' if plan.automation else 'No'}",
            "",
            "## Preconditions",
            ""
        ]

        for index, condition in enumerate(plan.preconditions, 1):
            lines.append(f"{index}. {condition}")

        lines.extend([
            "",
            "## Test Steps",
            "",
            "| Step | Action | Expected Result |",
            "|---:|---|---|",
        ])

        for step in plan.steps:
            lines.append(
                f"| {step.step_number} | "
                f"{step.action} | "
                f"{step.expected_result} |"
            )

        lines.extend([
            "",
            "## Overall Expected Result",
            "",
            plan.expected_result,
            "",
        ])

        return "\n".join(lines)


import asyncio

USER_REQUIREMENTS = """
Automate the SauceDemo login functionality.

Scope:
- Application: https://www.saucedemo.com/
- Feature: Login
- Scenario: One happy-path login scenario only.
- Do not create Jira issues.
- Do not create a QA strategy.
- Do not test logout, invalid login, locked users, cart,
  checkout, products, or any other functionality.

Happy credentials:
username: "standard_user"
password: "secret_sauce" 

Happy-path scenario:
1. Open SauceDemo.
2. Enter a valid username.
3. Enter the corresponding valid password.
4. Click Login.
5. Verify that the Products page is displayed successfully.

Create exactly ONE test scenario.
"""


async def main():
    client = MCPClient(mcp_config())

    try:
        print("\n🔌 Connecting to Playwright MCP...", flush=True)
        tools = await client.connect()

        print(
            f"✅ Connected. Discovered {len(tools)} MCP tools.",
            flush=True,
        )
        print("\n🔎 Starting browser exploration...", flush=True)

        playwright_agent = PlaywrightAgent(tools)

        exploration: ExplorationResult = await playwright_agent.agent_explore(
            url="https://www.saucedemo.com/",
            scenario="Successful login with valid credentials",
        )
        print("✅ Browser exploration completed.", flush=True)

        print("\n🧠 Starting Planner / Qwen3...", flush=True)

        planner = PlaywrightPlanner()

        # ---------------------------------------------------------
        # 1. Register test scenario
        # ---------------------------------------------------------
        registry = TestRegistry()

        scenario = TestScenario(
            application="saucedemo",
            feature="login",
            scenario="successful_login",
            expected="Products page is displayed after successful login",
        )

        test_record: TestRecord = registry.register_test(scenario)

        print(f"\n🆔 Test Case ID: {test_record.test_case_id}")
        print(f"📌 Registry Status: {test_record.status}")

        # ---------------------------------------------------------
        # 2. Generate test plan
        # ---------------------------------------------------------

        plan: TestPlan = await planner.create_plan(
            user_requirements=USER_REQUIREMENTS,
            exploration=exploration,
            test_case_id=test_record.test_case_id,
        )

        # ---------------------------------------------------------
        # 3. Validate test plan
        # ---------------------------------------------------------

        errors = TestPlanValidator.validate(plan)

        if errors:
            print("\n❌ TEST PLAN VALIDATION FAILED")

            for error in errors:
                print(f"   • {error}")

            return

        print("\n✅ Test plan validation passed.")

        # ---------------------------------------------------------
        # 4. Render Markdown
        # ---------------------------------------------------------

        markdown: str = planner.render_markdown(plan)

        # ---------------------------------------------------------
        # 5. Persist Markdown artifact
        # ---------------------------------------------------------

        artifact_store = PlaywrightArtifactStore()

        path = artifact_store.write_test_plan(markdown)

        print(f"\n📄 Test plan written to: {path}")

        # ---------------------------------------------------------
        # 6. Display plan
        # ---------------------------------------------------------

        print("\n📋 GENERATED TEST PLAN")
        print("=" * 70)
        print(markdown)

    finally:
        await client.close()


if __name__ == "__main__":
    asyncio.run(main())
